<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Preparation – AD688 Career Evaluation Product</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-445b8638c3d06994fee0907d791121c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">AD688 Career Evaluation Product</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./introduction.html"> 
<span class="menu-text">Project Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./data_cleaning.html" aria-current="page"> 
<span class="menu-text">Data Preparation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./eda.html"> 
<span class="menu-text">Exploratory Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./skill_gap_analysis.html"> 
<span class="menu-text">Skill Gap Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./career_evaluation.html"> 
<span class="menu-text">Evaluation Logic</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ml_methods.html"> 
<span class="menu-text">Predictive Modeling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./career_plan.html"> 
<span class="menu-text">Career Strategy</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose">Purpose</a></li>
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source">Data Source</a></li>
  <li><a href="#industry-and-career-scope" id="toc-industry-and-career-scope" class="nav-link" data-scroll-target="#industry-and-career-scope">Industry and Career Scope</a>
  <ul class="collapse">
  <li><a href="#why-this-industry-and-why-a-three-digit-code" id="toc-why-this-industry-and-why-a-three-digit-code" class="nav-link" data-scroll-target="#why-this-industry-and-why-a-three-digit-code">Why this industry, and why a three-digit code</a></li>
  </ul></li>
  <li><a href="#role-definition" id="toc-role-definition" class="nav-link" data-scroll-target="#role-definition">Role Definition</a></li>
  <li><a href="#filter-funnel" id="toc-filter-funnel" class="nav-link" data-scroll-target="#filter-funnel">Filter Funnel</a></li>
  <li><a href="#cleaning-decisions" id="toc-cleaning-decisions" class="nav-link" data-scroll-target="#cleaning-decisions">Cleaning Decisions</a>
  <ul class="collapse">
  <li><a href="#field-normalization" id="toc-field-normalization" class="nav-link" data-scroll-target="#field-normalization">Field Normalization</a></li>
  </ul></li>
  <li><a href="#data-quality-and-limitations" id="toc-data-quality-and-limitations" class="nav-link" data-scroll-target="#data-quality-and-limitations">Data Quality and Limitations</a></li>
  <li><a href="#output" id="toc-output" class="nav-link" data-scroll-target="#output">Output</a></li>
  <li><a href="#reproducing-this-step" id="toc-reproducing-this-step" class="nav-link" data-scroll-target="#reproducing-this-step">Reproducing This Step</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data Preparation</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="purpose" class="level2">
<h2 class="anchored" data-anchor-id="purpose">Purpose</h2>
<p>Every figure on the analysis pages comes from one table. This page documents how that table was built: what was pulled, what was kept, what was removed, and what was repaired. Anyone reading the conclusions should be able to judge how much weight the evidence can carry.</p>
</section>
<section id="data-source" class="level2">
<h2 class="anchored" data-anchor-id="data-source">Data Source</h2>
<p>The panel is built from the <strong>WRDS jobs_2026 dataset</strong> supplied for Module 3: <strong>504,208 postings across 134 columns</strong>, distributed as twenty-one Parquet parts with a manifest, per-column coverage report and checksums.</p>
<p>Modules 1 and 2 used the MET Employability Career Match API. The analysis moved to the supplied dataset in Module 3 and measured the two sources against each other on the exact scope before moving forward:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>MET API panel</th>
<th>Module 3, as supplied</th>
<th>Module 3, after cleaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Postings in scope</td>
<td>6,199</td>
<td>7,074</td>
<td><strong>7,074</strong></td>
</tr>
<tr class="even">
<td>Skills listed</td>
<td>93%</td>
<td>100%</td>
<td><strong>100%</strong></td>
</tr>
<tr class="odd">
<td>US state recorded</td>
<td>28%</td>
<td>92%</td>
<td><strong>73%</strong></td>
</tr>
<tr class="even">
<td>Minimum education level</td>
<td>59%, parsed from text</td>
<td>69%</td>
<td><strong>69%, a coded field</strong></td>
</tr>
<tr class="odd">
<td>Work arrangement recorded</td>
<td>48%</td>
<td>65%</td>
<td><strong>44%</strong></td>
</tr>
<tr class="even">
<td>Annual salary usable</td>
<td>19%</td>
<td>25%</td>
<td><strong>25%</strong></td>
</tr>
<tr class="odd">
<td>Years of experience</td>
<td>66%, parsed from text</td>
<td>56%</td>
<td><strong>24%, a numeric field</strong></td>
</tr>
<tr class="even">
<td>Occupation code (SOC)</td>
<td>98%</td>
<td>33%</td>
<td><strong>33%, and unreliable</strong></td>
</tr>
</tbody>
</table>
<p>The third and fourth columns differ because several supplied fields encode missing data as a value rather than as a blank. Those cases are set out under Field Normalization below.</p>
<p>The switch is not an improvement on every axis. Occupational coding is substantially sparser and, as found upon inspection, unreliable where it is present. Experience is recorded on fewer postings once placeholder values are removed, though what remains is a number rather than a figure that is extracted with a regular expression. Geography was the single largest limitation of the earlier panel and it improves by a factor of two and a half even after cleaning, the skill fields arrive split into named tools, specialisations, transferable skills and certifications, and education and experience stop being the team’s estimates and become the provider’s.</p>
</section>
<section id="industry-and-career-scope" class="level2">
<h2 class="anchored" data-anchor-id="industry-and-career-scope">Industry and Career Scope</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td>Industry code</td>
<td>NAICS 2022 — <strong>523</strong>, Securities, Commodity Contracts, and Other Financial Investments and Related Activities</td>
</tr>
<tr class="even">
<td>Career pathway</td>
<td>Business Intelligence / Data Analyst</td>
</tr>
<tr class="odd">
<td>Date window</td>
<td>Postings published on or after <strong>1 September 2025</strong></td>
</tr>
<tr class="even">
<td>Build date</td>
<td>4 October 2026</td>
</tr>
</tbody>
</table>
<p>The date window keeps the analysis current: the source spans postings back to 2014, and hiring requirements from a decade ago describe a market the target user is not applying into. In practice the window costs little — only 192 in-scope postings predate it.</p>
<section id="why-this-industry-and-why-a-three-digit-code" class="level3">
<h3 class="anchored" data-anchor-id="why-this-industry-and-why-a-three-digit-code">Why this industry, and why a three-digit code</h3>
<p>Module 1 anchored the project to NAICS 5221, Depository Credit Intermediation. That code returned 59 postings in total, too few to support compensation or skill-gap analysis, and lead to the analysis being re-anchored to NAICS 523 after measuring the neighbouring codes. NAICS 523 accounts for roughly two-thirds of all analytics postings within Finance and Insurance, so it is where the market actually is.</p>
<p>The assignment asks for four- or six-digit codes where possible. The earlier source carried no four-digit granularity beneath 523; this dataset does expose NAICS4 through NAICS6, and those columns are retained in the panel for finer analysis, but 523 remains the scope boundary so that the project stays comparable across modules.</p>
</section>
</section>
<section id="role-definition" class="level2">
<h2 class="anchored" data-anchor-id="role-definition">Role Definition</h2>
<p>The assignment allows title keywords, SOC or O*NET mappings, skills logic, or a combination, provided the choice is explained. For this analysis, the team uses a <strong>combination</strong>, and this dataset makes the case stronger than before: occupation codes are present on only a third of postings, so an occupation-only filter would discard two postings in three unseen.</p>
<p>A posting is kept when <strong>either</strong> condition holds:</p>
<ul>
<li>its SOC occupation matches one of: data scientist, database architect, statistician, mathematician, operations research, market research analyst, financial and investment analyst, credit analyst, management analyst</li>
<li><strong>or</strong> its title contains one of: analyst, analytics, data, business intelligence, BI, reporting, SQL, data science, machine learning</li>
</ul>
<p>Information-security roles are then removed. They match the word “analyst” but belong to a different career pathway, and including them would distort the skill profile the product reports.</p>
</section>
<section id="filter-funnel" class="level2">
<h2 class="anchored" data-anchor-id="filter-funnel">Filter Funnel</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Postings</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Source dataset</td>
<td>504,208</td>
</tr>
<tr class="even">
<td>In NAICS 523</td>
<td>24,914</td>
</tr>
<tr class="odd">
<td>Matched the role definition</td>
<td>8,747</td>
</tr>
<tr class="even">
<td>Removed: information-security roles</td>
<td>−76</td>
</tr>
<tr class="odd">
<td>Removed: no publication date</td>
<td>−1,405</td>
</tr>
<tr class="even">
<td>Removed: published before 1 September 2025</td>
<td>−192</td>
</tr>
<tr class="odd">
<td>Removed: duplicate identifiers</td>
<td>−0</td>
</tr>
<tr class="even">
<td>Removed: missing an essential field</td>
<td>−0</td>
</tr>
<tr class="odd">
<td><strong>Analytical panel</strong></td>
<td><strong>7,074</strong></td>
</tr>
</tbody>
</table>
<p>Postings without a publication date are the largest single exclusion. They cannot be placed inside the date window, and keeping them would mean reporting a twelve-month market using rows of unknown age.</p>
</section>
<section id="cleaning-decisions" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-decisions">Cleaning Decisions</h2>
<p>Cleaning stays conservative. Where a value is implausible a blank is inserted into that field rather than an assumed a replacement, and where a whole posting is questionable it is recorded as a gap. Deleting rows narrows the sample; blanking one field costs only that field.</p>
<p>The rules below were written for Module 2 by Katie Bowles and carried over unchanged; only the column names differ, and the salary handling is extended because this dataset quotes pay in several periods.</p>
<p><strong>Duplicates.</strong> Deduplicated on the posting identifier. None remained.</p>
<p><strong>Rows missing essentials.</strong> A posting is dropped if it has no identifier, title, employer or publication date. After the date filter, none failed this test.</p>
<p><strong>Dates.</strong> Parsed to a single format. Where an expiry date preceded the publication date the expiry would be blanked, since one of the two must be wrong and it cannot be determined which is incorrect; no postings were affected.</p>
<p><strong>Salary.</strong> The provider’s <code>SALARY</code> column turned out to be a free-text summary whose value is an empty placeholder on most rows, so it is kept for reference but never used as a figure. The usable numbers are the structured range, and that range is quoted in different periods — 1,751 annual, 315 hourly, 18 monthly. Each is validated against bounds appropriate to its own period rather than a single annual rule, which had been silently deleting hourly rates as “implausible”. Reversed ranges are swapped, zeros treated as missing, and 20 rows were cleared as out of range across all periods.</p>
<p>Hourly and monthly rates are kept in their own columns and <strong>are not converted to annual figures</strong>, because the conversion requires an assumption about hours worked that the postings do not supply. <code>ANNUAL_SALARY_MID</code> — the midpoint of the annual range — is the field used for salary analysis, and it is populated on 1,741 postings.</p>
<p><strong>Experience and education.</strong> Taken directly from the provider’s coded fields. Unlike the earlier panel these are not team estimates, so no parsing decisions were needed.</p>
<p><strong>Skills.</strong> Arrive as arrays and are stored as JSON-style list strings — for example <code>["Microsoft Excel", "SQL (Programming Language)"]</code> — across four fields: all skills, named software, specialised skills and transferable skills, plus certifications. Names are not yet normalised, so casing and synonyms remain distinct; that normalisation belongs to the skill-gap work, where it has an analytical purpose. Code reading these fields must parse the list rather than splitting on a delimiter.</p>
<p><strong>Remote status.</strong> Never inferred, and category labels are normalised because the source spells the same category two ways. A posting with no remote label is an absence of information, not evidence of an office requirement.</p>
<p><strong>Location.</strong> Text fields trimmed of stray whitespace. This dataset carries no coordinates, so the latitude and longitude check from the earlier pipeline does not apply; geography is carried by state, city and metropolitan area.</p>
<p><strong>Types.</strong> Every column is cast explicitly — dates, booleans, numbers and categories — so later analysis cannot silently treat a number as text.</p>
<section id="field-normalization" class="level3">
<h3 class="anchored" data-anchor-id="field-normalization">Field Normalization</h3>
<p>Integration testing in Module 3 exposed four defects that coverage statistics alone do not reveal. Each repair is written to a separate column, so the provider’s original value stays auditable.</p>
<p><strong>The job title is overwritten on part of the panel.</strong> On 2,165 postings — 31 percent — <code>TITLE_NAME</code> holds the occupation name instead of the advertised title, so a vacancy posted as “Sr Financial Analyst, AWS GTM Finance” reads simply as “Management Analysts”. Counting titles from that field produced an apparent leading title of “management analysts” with 1,991 postings, which is an artifact of the coding and not a fact about the market. <code>TITLE_CLEAN</code> is rebuilt from the raw title text instead, raising the number of distinct titles from 2,396 to 4,000.</p>
<p><strong>Occupational coding is wrong on identifiable rows, not merely sparse.</strong> Several postings titled Senior Financial Analyst are coded as <strong>Models, Demonstrators, and Product Promoters</strong>. The field is kept and the defect reported rather than deleted, because it is the direct justification for defining roles by title as well as by code.</p>
<p><strong>The state field is not only a state field.</strong> It mixes full names with two-letter codes, so New York appeared twice — as “New York” (514) and as “NY” (212) — and it carries 1,202 postings labelled “United States” and 178 labeled “Remote”, a country and a work arrangement. <code>STATE_CLEAN</code> expands the codes and discards the non-geographic values, which lowers real coverage from an apparent 92 percent to an honest <strong>73 percent</strong>.</p>
<p><strong>Two fields encode “missing” as a value.</strong> <code>REMOTE_TYPE_NAME</code> carries a literal “Unknown” on 1,442 postings alongside 2,506 true nulls, and spells the office category both “Onsite” and “On-site”; <code>REMOTE_CLEAN</code> merges the spellings and treats “Unknown” as missing, leaving 44 percent labelled. <code>MIN_YEARS_EXPERIENCE</code> reports zero years on 2,288 postings, but on 2,143 of them the stated maximum is exactly one — a fixed “0 to 1” band attached to postings titled Senior Financial Analyst, Finance Manager and Accounting Manager. That is a provider default, and left in place it produced a median requirement of zero years across the panel. <code>MIN_YEARS_EXP_CLEAN</code> removes the band, leaving 1,702 postings with a stated requirement and a median of three years.</p>
<p>Several headline numbers fall as a result. That is the intended outcome: the higher figures counted placeholders as data.</p>
<p>A fifth defect surfaced in Module 5, in the employer field. On 397 postings it holds an applicant-tracking hostname rather than a company name, on 229 it names a staffing agency or job aggregator rather than the hiring firm, and one employer appeared under three spellings. The provider’s own <code>COMPANY_IS_STAFFING</code> flag cannot be used to find these: it is set on 93 of 7,074 rows and contradicts itself, marking TD as staffing while giving JPMorgan Chase both values. <code>EMPLOYER_CLEAN</code>, <code>EMPLOYER_UNIDENTIFIED</code> and <code>IS_AGENCY</code> record the repair without dropping any rows, so employer concentration is measured on the 6,448 postings where a hiring firm can actually be identified.</p>
</section>
</section>
<section id="data-quality-and-limitations" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-and-limitations">Data Quality and Limitations</h2>
<p>Coverage in the panel of 7,074 postings:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Populated</th>
<th>Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Skills</td>
<td>7,074</td>
<td>100%</td>
</tr>
<tr class="even">
<td>Named software skills</td>
<td>7,074</td>
<td>100%</td>
</tr>
<tr class="odd">
<td>US state, after normalization</td>
<td>5,135</td>
<td>73%</td>
</tr>
<tr class="even">
<td>Minimum education level</td>
<td>4,913</td>
<td>69%</td>
</tr>
<tr class="odd">
<td>Work arrangement, after normalization</td>
<td>3,126</td>
<td>44%</td>
</tr>
<tr class="even">
<td>Occupation code (SOC 2021)</td>
<td>2,357</td>
<td>33%</td>
</tr>
<tr class="odd">
<td>Annual salary usable</td>
<td>1,741</td>
<td>25%</td>
</tr>
<tr class="even">
<td>Years of experience, after normalization</td>
<td>1,702</td>
<td>24%</td>
</tr>
</tbody>
</table>
<p>Four limitations shape how the analysis pages should be read.</p>
<p><strong>Salary is disclosed on one posting in four.</strong> Employers who publish pay ranges are not a random sample — pay-transparency law applies in some states and not others — so the disclosed group likely skews toward those jurisdictions and toward larger employers. Every salary figure in this project describes that subset, not the market.</p>
<p><strong>Occupation codes are sparse and partly wrong.</strong> Only a third of postings carry a SOC occupation, and within that third the classification misassigns senior finance roles badly enough to be caught by eye. Any breakdown by occupation describes the coded third, and comparisons between occupations are ratios within that subset rather than counts of the whole market.</p>
<p><strong>Titles are dependable, classifications are not.</strong> Raw title text is present on every posting and is what is counted. Provider-normalised titles and occupation codes are used only where the analysis is explicitly about data quality.</p>
<p><strong>Experience survives on one posting in four.</strong> The provider supplies a value more often than that, but most of the additional rows carry a placeholder band rather than a requirement. It is a reliable number where present, but absence is common and should not be read as “no experience required”.</p>
<p>Against that, geography and skills are close to complete, which means the location analysis and the skill-gap work — the parts the product most depends on — rest on much firmer ground than the compensation analysis does.</p>
</section>
<section id="output" class="level2">
<h2 class="anchored" data-anchor-id="output">Output</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Analytical panel</strong></td>
<td><strong><code>data/processed/career_market_panel.csv</code> — 7,074 rows, 57 columns</strong></td>
</tr>
<tr class="even">
<td>Data dictionary</td>
<td><code>outputs/data_dictionary.md</code> and <code>outputs/data_dictionary.csv</code></td>
</tr>
<tr class="odd">
<td>Build log</td>
<td><code>outputs/m3_panel_build_log.md</code></td>
</tr>
<tr class="even">
<td>Normalization log</td>
<td><code>outputs/m3_normalization_log.md</code></td>
</tr>
<tr class="odd">
<td>Employer cleanup log</td>
<td><code>outputs/m5_employer_cleanup_log.md</code></td>
</tr>
<tr class="even">
<td>Baseline numbers</td>
<td><code>outputs/m3_baseline_numbers.md</code></td>
</tr>
</tbody>
</table>
<p>The source Parquet files are kept locally and excluded from version control; at roughly a gigabyte they are not needed to reproduce the analysis from the panel.</p>
</section>
<section id="reproducing-this-step" class="level2">
<h2 class="anchored" data-anchor-id="reproducing-this-step">Reproducing This Step</h2>
<ol type="1">
<li>Download the Module 3 dataset into <code>data/raw/m3_dataset/</code></li>
<li><code>pip install -r requirements.txt</code></li>
<li><code>python notebooks/19_build_panel_wrds.py</code> — scope filter, role filter, cleaning</li>
<li><code>python notebooks/21_fix_salary.py</code> — period-aware salary validation</li>
<li><code>python notebooks/23_normalize_panel.py</code> — field normalization</li>
<li><code>python notebooks/24_clean_employers.py</code> — employer cleanup</li>
<li><code>python notebooks/22_data_dictionary_m3.py</code> — data dictionary</li>
<li><code>python notebooks/15_market_baseline_figures.py</code> — baseline figures</li>
</ol>
<p>The scripts must run in that order: normalization depends on the salary step, and the dictionary and figures both read the normalized panel.</p>
<p>All work runs on the course AWS EC2 environment.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" role="list">

</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jchenbu\.github\.io\/ad688-career-evaluation-group1\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>