<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Predictive Modeling – AD688 Career Evaluation Product</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-445b8638c3d06994fee0907d791121c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">AD688 Career Evaluation Product</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./introduction.html"> 
<span class="menu-text">Project Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data_cleaning.html"> 
<span class="menu-text">Data Preparation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./eda.html"> 
<span class="menu-text">Exploratory Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./skill_gap_analysis.html"> 
<span class="menu-text">Skill Gap Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./career_evaluation.html"> 
<span class="menu-text">Evaluation Logic</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./ml_methods.html" aria-current="page"> 
<span class="menu-text">Predictive Modeling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./career_plan.html"> 
<span class="menu-text">Career Strategy</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#purpose" id="toc-purpose" class="nav-link active" data-scroll-target="#purpose">Purpose</a></li>
  <li><a href="#track-1-regression-what-skills-are-worth" id="toc-track-1-regression-what-skills-are-worth" class="nav-link" data-scroll-target="#track-1-regression-what-skills-are-worth">Track 1 — Regression: What Skills Are Worth</a>
  <ul class="collapse">
  <li><a href="#what-was-modeled" id="toc-what-was-modeled" class="nav-link" data-scroll-target="#what-was-modeled">What was modeled</a></li>
  <li><a href="#why-it-matters-for-a-job-seeker" id="toc-why-it-matters-for-a-job-seeker" class="nav-link" data-scroll-target="#why-it-matters-for-a-job-seeker">Why it matters for a job seeker</a></li>
  <li><a href="#what-variables-were-used" id="toc-what-variables-were-used" class="nav-link" data-scroll-target="#what-variables-were-used">What variables were used</a></li>
  <li><a href="#how-performance-was-evaluated" id="toc-how-performance-was-evaluated" class="nav-link" data-scroll-target="#how-performance-was-evaluated">How performance was evaluated</a></li>
  <li><a href="#what-the-result-means-in-practical-career-terms" id="toc-what-the-result-means-in-practical-career-terms" class="nav-link" data-scroll-target="#what-the-result-means-in-practical-career-terms">What the result means in practical career terms</a></li>
  </ul></li>
  <li><a href="#track-2-classification-which-postings-are-reachable" id="toc-track-2-classification-which-postings-are-reachable" class="nav-link" data-scroll-target="#track-2-classification-which-postings-are-reachable">Track 2 — Classification: Which Postings Are Reachable</a>
  <ul class="collapse">
  <li><a href="#what-was-modeled-1" id="toc-what-was-modeled-1" class="nav-link" data-scroll-target="#what-was-modeled-1">What was modeled</a></li>
  <li><a href="#why-it-matters-for-a-job-seeker-1" id="toc-why-it-matters-for-a-job-seeker-1" class="nav-link" data-scroll-target="#why-it-matters-for-a-job-seeker-1">Why it matters for a job seeker</a></li>
  <li><a href="#what-variables-were-used-1" id="toc-what-variables-were-used-1" class="nav-link" data-scroll-target="#what-variables-were-used-1">What variables were used</a></li>
  <li><a href="#how-performance-was-evaluated-1" id="toc-how-performance-was-evaluated-1" class="nav-link" data-scroll-target="#how-performance-was-evaluated-1">How performance was evaluated</a></li>
  <li><a href="#what-the-result-means-in-practical-career-terms-1" id="toc-what-the-result-means-in-practical-career-terms-1" class="nav-link" data-scroll-target="#what-the-result-means-in-practical-career-terms-1">What the result means in practical career terms</a></li>
  </ul></li>
  <li><a href="#what-the-two-models-say-together" id="toc-what-the-two-models-say-together" class="nav-link" data-scroll-target="#what-the-two-models-say-together">What The Two Models Say Together</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#reproducing-this-step" id="toc-reproducing-this-step" class="nav-link" data-scroll-target="#reproducing-this-step">Reproducing This Step</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predictive Modeling</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="purpose" class="level2">
<h2 class="anchored" data-anchor-id="purpose">Purpose</h2>
<p>The earlier pages describe what the market looks like. This page asks a narrower question, the one Module 5 was built around: <strong>which skills most strongly distinguish stronger opportunities from weaker ones?</strong></p>
<p>“Stronger” is defined two ways, because a job seeker cares about two different things. A stronger posting pays more, and a stronger posting is one they can realistically get. Each definition gets its own model.</p>
<p>Both models read the same input: a binary indicator for each of the <strong>179 skills that appear in at least one percent of the panel</strong>, built once in <code>notebooks/30_build_features.py</code>. Postings list a median of ten skills each, drawn from 3,327 distinct names.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The skill field is stored as a JSON list, not as delimited text. Splitting it on a separator silently collapses an entire posting into a single skill, which produces plausible-looking but meaningless counts. The feature builder parses it.</p>
</div>
</div>
<hr>
</section>
<section id="track-1-regression-what-skills-are-worth" class="level2">
<h2 class="anchored" data-anchor-id="track-1-regression-what-skills-are-worth">Track 1 — Regression: What Skills Are Worth</h2>
<section id="what-was-modeled" class="level3">
<h3 class="anchored" data-anchor-id="what-was-modeled">What was modeled</h3>
<p>The natural logarithm of the annual salary midpoint, predicted from the skills a posting lists. Pay is heavily right-skewed in this panel, from $25,000 to $696,000 against a median of $112,500, so a model on the raw figure would chase a handful of very large ranges. Working in logs also makes each coefficient readable as an approximate percentage effect on pay.</p>
<p>Two specifications were fitted. The first uses skills alone. The second adds the ten largest states and the work arrangement as controls, so that the skill effects can be separated from the simple fact that some cities pay more.</p>
</section>
<section id="why-it-matters-for-a-job-seeker" class="level3">
<h3 class="anchored" data-anchor-id="why-it-matters-for-a-job-seeker">Why it matters for a job seeker</h3>
<p>A candidate choosing what to learn next is making an investment decision. Knowing which skills sit in better-paid postings turns that choice from guesswork into something measurable.</p>
</section>
<section id="what-variables-were-used" class="level3">
<h3 class="anchored" data-anchor-id="what-variables-were-used">What variables were used</h3>
<p>179 binary skill indicators, plus 13 geography and work-arrangement controls in the second specification. Fitted on the <strong>1,741 postings (25 percent of the panel) that disclose pay</strong>, with ridge regularisation and the penalty chosen by cross-validation.</p>
</section>
<section id="how-performance-was-evaluated" class="level3">
<h3 class="anchored" data-anchor-id="how-performance-was-evaluated">How performance was evaluated</h3>
<p>A quarter of the postings were held out and never used in fitting. Results are reported on that held-out set and confirmed with five-fold cross-validation.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Held-out R²</th>
<th>Cross-validated R²</th>
<th>RMSE</th>
<th>MAE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Predict the median for everyone</td>
<td>−0.014</td>
<td>—</td>
<td>$51,224</td>
<td>$36,576</td>
</tr>
<tr class="even">
<td>Skills only</td>
<td>0.366</td>
<td>0.299 (sd 0.034)</td>
<td>$40,930</td>
<td>$28,751</td>
</tr>
<tr class="odd">
<td><strong>Skills + geography and remote status</strong></td>
<td><strong>0.373</strong></td>
<td><strong>0.319</strong> (sd 0.036)</td>
<td><strong>$40,821</strong></td>
<td><strong>$28,552</strong></td>
</tr>
</tbody>
</table>
<p>Two things stand out. The skill mix explains roughly a third of the variation in pay, which is substantial for a model that reads nothing but a list of keywords. And <strong>adding geography barely moves the result</strong> — 0.366 to 0.373. In this industry, what the job asks for matters more than where it is.</p>
</section>
<section id="what-the-result-means-in-practical-career-terms" class="level3">
<h3 class="anchored" data-anchor-id="what-the-result-means-in-practical-career-terms">What the result means in practical career terms</h3>
<p><img src="figures/fig_salary_coefficients.png" class="img-fluid"></p>
<p>Coefficients are reported only for the 107 skills appearing in at least 30 of the salaried postings; 72 rarer skills were estimated but are not shown, because a coefficient fitted on a handful of rows is noise rather than a finding.</p>
<p><strong>Skills associated with higher pay:</strong> advanced analytics (+22%), executive leadership (+20%), data architecture (+19%), technical accounting (+18%), public accounting (+17%), data science (+17%), fixed income (+15%), capital markets (+15%).</p>
<p><strong>Skills associated with lower pay:</strong> problem solving (−28%), financial data (−19%), customer service (−16%), organizational skills (−12%), Microsoft Office (−12%), financial analysis (−9%), Microsoft Excel (−9%), Power BI (−9%).</p>
<p>The pattern is not “technical versus non-technical”. It is <strong>specific versus generic</strong>. Compare the pairs: “financial analysis” costs 9 percent, while “fixed income” and “capital markets” each add 15. “Problem solving” costs 28 percent, while “data architecture” adds 19. The same holds for tools — Microsoft Excel appears in 779 of the salaried postings and is associated with lower pay, while Power BI, a real BI tool, carries no premium either.</p>
<p>A direct comparison of the top and bottom salary quartiles makes the division concrete:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Skill</th>
<th>Top quartile (≥ $141,500)</th>
<th>Bottom quartile (≤ $87,500)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Python</td>
<td>33.0%</td>
<td>9.8%</td>
</tr>
<tr class="even">
<td>SQL</td>
<td>35.0%</td>
<td>19.2%</td>
</tr>
<tr class="odd">
<td>Data science</td>
<td>12.6%</td>
<td>0.0%</td>
</tr>
<tr class="even">
<td>Machine learning</td>
<td>7.6%</td>
<td>0.0%</td>
</tr>
<tr class="odd">
<td>Microsoft Excel</td>
<td>25.6%</td>
<td>51.8%</td>
</tr>
<tr class="even">
<td>Microsoft Office</td>
<td>5.0%</td>
<td>27.5%</td>
</tr>
</tbody>
</table>
<p>Data science and machine learning appear in <strong>no bottom-quartile posting at all</strong>. Excel appears in over half of them.</p>
<p>The honest limit: two thirds of the variation in pay remains unexplained, and the average error is still $28,500. This model narrows a guess; it does not price a job.</p>
<hr>
</section>
</section>
<section id="track-2-classification-which-postings-are-reachable" class="level2">
<h2 class="anchored" data-anchor-id="track-2-classification-which-postings-are-reachable">Track 2 — Classification: Which Postings Are Reachable</h2>
<section id="what-was-modeled-1" class="level3">
<h3 class="anchored" data-anchor-id="what-was-modeled-1">What was modeled</h3>
<p>Whether a posting is entry level or advanced, predicted from its skills. Postings stating a requirement of two years or less are labelled entry level; the rest are advanced. The split is <strong>542 entry against 1,160 advanced</strong>, so the classes are imbalanced and the model was fitted with balanced class weights.</p>
</section>
<section id="why-it-matters-for-a-job-seeker-1" class="level3">
<h3 class="anchored" data-anchor-id="why-it-matters-for-a-job-seeker-1">Why it matters for a job seeker</h3>
<p>The <a href="./eda.html">Market Baseline</a> established that this is a mid-career market: where a requirement is stated at all, the median is three years. A student leaving a programme is competing for the smaller share. A model that can read seniority from the skill list lets them filter a job board down to the postings actually worth an application.</p>
</section>
<section id="what-variables-were-used-1" class="level3">
<h3 class="anchored" data-anchor-id="what-variables-were-used-1">What variables were used</h3>
<p>The same 179 skill indicators, fitted on the <strong>1,702 postings (24 percent) that state an experience requirement</strong>, with logistic regression and the penalty chosen by cross-validation.</p>
</section>
<section id="how-performance-was-evaluated-1" class="level3">
<h3 class="anchored" data-anchor-id="how-performance-was-evaluated-1">How performance was evaluated</h3>
<p>The same held-out quarter, judged on precision and recall for each class rather than on accuracy alone.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Model</th>
<th>Majority-class baseline</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accuracy</td>
<td>0.678</td>
<td><strong>0.681</strong></td>
</tr>
<tr class="even">
<td>ROC AUC</td>
<td>0.741</td>
<td>0.500</td>
</tr>
<tr class="odd">
<td>Entry: precision / recall / F1</td>
<td>0.50 / <strong>0.67</strong> / 0.57</td>
<td>— / <strong>0.00</strong> / —</td>
</tr>
<tr class="even">
<td>Advanced: precision / recall / F1</td>
<td>0.81 / 0.68 / 0.74</td>
<td>0.68 / 1.00 / 0.81</td>
</tr>
</tbody>
</table>
<p><img src="figures/fig_seniority_confusion.png" class="img-fluid"></p>
<p><strong>The model does not beat the baseline on accuracy, and we report that plainly.</strong> It is marginally worse, 0.678 against 0.681. But accuracy is the wrong measure here. The baseline reaches 68 percent by calling every posting advanced, which means it identifies <strong>zero</strong> of the openings a student could apply to. The model finds 91 of 136. For a product whose job is to say “apply here”, that difference is the entire value, and an AUC of 0.741 confirms the signal is real rather than noise.</p>
<p>The cost is visible in the matrix: 45 entry-level postings were missed, and 92 advanced postings were wrongly flagged as reachable. A candidate using this filter will waste some applications. That is the better error to make — a wasted application costs an hour, a missed opening costs the job.</p>
</section>
<section id="what-the-result-means-in-practical-career-terms-1" class="level3">
<h3 class="anchored" data-anchor-id="what-the-result-means-in-practical-career-terms-1">What the result means in practical career terms</h3>
<p><img src="figures/fig_seniority_coefficients.png" class="img-fluid"></p>
<p>Two skills separate completely — every posting listing <strong>data architecture</strong> (52 postings, 100 percent advanced) and <strong>treasury management</strong> (57 postings, 98 percent) falls on the senior side. For these the direction is certain but the magnitude is an artifact, so only the direction is reported.</p>
<p>Among the rest, the <strong>markers of a senior posting are consistently specific</strong>: data governance (97 percent advanced), information technology (97 percent), bank secrecy act (98 percent), technical accounting (88 percent), general ledger (85 percent), risk analytics (83 percent).</p>
<p>The entry-level signal is much weaker, and this is itself a finding. Against a base rate of 68 percent advanced, only a few skills sit meaningfully below it: research (28 percent advanced), employee benefits (44 percent), business development (47 percent), data analysis tools (50 percent). Most of the remaining “entry markers” sit within a few points of the base rate. <strong>Postings announce seniority clearly; they do not announce accessibility.</strong></p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>A caution on reading coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p>A logistic coefficient is conditional on every other skill in the posting; the raw share of advanced postings is not. For 21 of the 107 skills the two disagree — “sales” carries the strongest entry-level coefficient in the model, yet 69 percent of postings listing it are advanced, slightly above the base rate. Where the two measures conflict, the effect is a product of correlation between skills and is not reported here as a property of the skill. Only skills where both point the same way appear in the lists above.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="what-the-two-models-say-together" class="level2">
<h2 class="anchored" data-anchor-id="what-the-two-models-say-together">What The Two Models Say Together</h2>
<p>They agree, and the agreement is the finding.</p>
<p><strong>Specificity is what the market pays for and promotes on.</strong> Across both models the same division appears: named capabilities — data architecture, data governance, technical accounting, fixed income, capital markets, bank secrecy act — sit in the well-paid and senior postings. Generic descriptors — problem solving, analytical skills, organizational skills, business acumen — sit in the cheap and junior ones. A candidate writing a CV should take this literally: “experienced with financial analysis” is the phrasing of a $90,000 posting, “fixed income attribution” is the phrasing of a $140,000 one.</p>
<p><strong>There is one skill set that pays well without demanding years.</strong> Machine learning appears in 7.6 percent of top-quartile postings and in none of the bottom quartile, yet on the seniority split it sits at the base rate — 67 percent advanced against 68 percent overall. The same broadly holds for data science. For a student leaving a programme, that combination is the clearest point of leverage in this data: a skill that raises the pay a posting offers without raising the experience it demands.</p>
<p><strong>Excel is the floor, not the ladder.</strong> It appears in 779 of the 1,741 salaried postings, more than any other skill, and is associated with lower pay in the model and with the bottom quartile in the raw comparison. It is necessary and it is not an advantage.</p>
<p>These three findings feed the <a href="./career_plan.html">Career Strategy</a> page, where they become specific actions.</p>
<hr>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p><strong>Both models describe disclosed subsets.</strong> Pay is stated on 25 percent of the panel and experience on 24 percent, and neither group is a random sample — pay-transparency law varies by state, and employers who state requirements may differ systematically from those who do not. Every number here describes the postings that told us, not the market.</p>
<p><strong>Association is not causation.</strong> Listing Python does not cause a posting to pay more. Python marks a different kind of role, and the role carries the pay. The practical reading is about which postings to target, not about what adding a line to a CV will do on its own.</p>
<p><strong>The feature set is deliberately narrow.</strong> Only skills are used, because the question was about skills. Employer, title seniority and city are not in the model, which is why the regression leaves two thirds of the variation unexplained.</p>
<p><strong>Skill names are the provider’s.</strong> They are normalised for case and bracketed qualifiers but not for synonyms, so closely related names are counted separately.</p>
</section>
<section id="reproducing-this-step" class="level2">
<h2 class="anchored" data-anchor-id="reproducing-this-step">Reproducing This Step</h2>
<ol type="1">
<li><code>python notebooks/30_build_features.py</code> — parse skills, build the feature matrix</li>
<li><code>python notebooks/31_regression_salary.py</code> — regression on compensation</li>
<li><code>python notebooks/32_classify_seniority.py</code> — classification of seniority</li>
</ol>
<p>Full numeric output is written to <code>outputs/m5_regression_log.md</code> and <code>outputs/m5_classification_log.md</code>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jchenbu\.github\.io\/ad688-career-evaluation-group1\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>